[project]
name = "clipboardgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clipboard>=0.0.4",
    "openai>=2.12.0",
    "plyer>=2.1.0",
    "pyautogui>=0.9.54",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "ipython>=9.8.0",
    "mypy>=1.19.1",
    "pylint>=4.0.4",
    "ruff>=0.14.9",
]
